repos:
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.384
    hooks:
      - id: pyright
        name: pyright (3.12)
        args: [--pythonversion=3.12]
        files: \.pyi?$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
      - id: ruff-format
