networks:
  main:
    external: true
    name: main

services:
  bot:
    container_name: graha-bot
    extra_hosts:
      - "database:host-gateway"
    image: ghcr.io/abstractumbra/graha:latest
    networks:
      main:
    restart: unless-stopped
    volumes:
      - ./configs/:/app/configs/:ro

version: "3"
