services:
  bot:
    container_name: graha
    extra_hosts:
      - "database:host-gateway"
    image: ghcr.io/abstractumbra/graha:latest
    restart: unless-stopped
    volumes:
      - ./configs/:/app/configs/:ro
      - ./logs/:/app/logs/:rw
      - ./extensions/:/app/extensions/:ro
      - ./.git/:/app/.git
      - ./.safe-gitconfig/:/root/.gitconfig

  webserver:
    container_name: graha-webserver
    extra_hosts:
      - "database:host-gateway"
    environment:
      - CSRF_SECRET_FILE=/var/run/secrets/csrf_token
    image: ghcr.io/abstractumbra/graha-webserver:latest
    restart: unless-stopped
    secrets:
      - csrf_token

secrets:
  csrf_token:
    file: webserver/csrf_token.txt
