networks:
  main:
    external: true
    name: main

services:
  bot:
    container_name: graha-bot
    extra_hosts:
      - "database:host-gateway"
    image: ghcr.io/abstractumbra/graha:latest
    networks:
      main:
    restart: unless-stopped
    volumes:
      - ./configs/:/app/configs/:ro
      - ./logs/:/app/logs/:rw
      - ./extensions/:/app/extensions/:ro
      - ./.git/:/app/.git
      - ./.safe-gitconfig/:/root/.gitconfig

version: "3"
