version: "3"

services:
  api:
    build:
      context: server/
      dockerfile: Dockerfile
    container_name: graha-api
    ports:
      - 127.0.0.1:10037:10037
    network_mode: host

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
    container_name: graha-bot
