networks:
  main:
    external: true
    name: main

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graha-bot
    extra_hosts:
      - "database:host-gateway"
    networks:
      main:
    volumes:
      - ./configs/:/app/configs/:ro

version: "3"
