[tool.poetry]
name = "Graha Tia"
version = "0.0.1"
description = "A helper bot for organizing your FFXIV needs."
authors = ["Alex Nørgaard <umbra@abstractumbra.dev>"]

[tool.poetry.dependencies]
python = "^3.11"
"discord.py" = { version = "^2", extras = ["speed"] }
discord-ext-menus = { git = "https://github.com/Rapptz/discord-ext-menus", rev = "master" }
jishaku = "*"
"mystbin.py" = "*"
asyncpg = "*"
sentry-sdk = "*"
lru-dict = "*"
parsedatetime = "*"
tomli = "*"
python-dateutil = "*"
psutil = "*"
pygit2 = "*"

[tool.poetry.group.dev.dependencies]
ruff = "*"
typing-extensions = "*"
asyncpg-stubs = "*"
"pre-commit" = "*"

[tool.poetry.group.speed.dependencies]
orjson = "*"

[tool.black]
line-length = 125
preview = true

[tool.ruff]
line-length = 125
exclude = ["docs/extensions/*.py"]
select = [
    "C4",
    "F",
    "G",
    "I",
    "PTH",
    "RUF",
    "SIM",
    "TCH",
    "UP",
    "W",
    "PERF",
    "ANN",
]
ignore = [
    "F401",
    "F402",
    "F403",
    "F405",
    "PERF203",
    "RUF001",
    "RUF009",
    "SIM105",
    "UP034",
    "UP038",
    "ANN101",
    "ANN102",
    "ANN401",
]
[tool.ruff.isort]
split-on-trailing-comma = true
combine-as-imports = true

[tool.ruff.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.flake8-quotes]
inline-quotes = "single"


[tool.pyright]
include = ["bot.py", "utilities/**/*.py", "extensions/**/*.py"]
useLibraryCodeForTypes = true
typeCheckingMode = "basic"
pythonVersion = "3.10"
strictListInference = true
strictDictionaryInference = true
strictSetInference = true
strictParameterNoneValue = true
reportMissingImports = "error"
reportUnusedImport = "error"
reportUnusedClass = "error"
reportUnusedFunction = "error"
reportUnusedVariable = "error"
reportGeneralTypeIssues = "error"
reportDuplicateImport = "error"
reportUntypedFunctionDecorator = "error"
reportUnnecessaryTypeIgnoreComment = "warning"


[build-system]
requires = ["poetry-core>=1.0.2b2"]
build-backend = "poetry.core.masonry.api"
