[tool.poetry]
name = "Graha Tia"
version = "0.0.1"
description = "A helper bot for organizing your FFXIV needs."
authors = ["Alex Nørgaard <umbra@abstractumbra.dev>"]

[tool.poetry.dependencies]
python = "^3.11"
"discord.py" = { version = "^2", extras = ["speed"] }
discord-ext-menus = { git = "https://github.com/Rapptz/discord-ext-menus", rev = "master" }
jishaku = "*"
"mystbin.py" = "*"
asyncpg = "*"
sentry-sdk = "*"
lru-dict = "*"
parsedatetime = "*"
tomli = "*"
python-dateutil = "*"
psutil = "*"
pygit2 = "*"
pendulum = "*"

[tool.poetry.group.dev.dependencies]
black = "*"
typing-extensions = "*"
asyncpg-stubs = "*"

[tool.poetry.group.speed.dependencies]
orjson = "*"

[tool.black]
line-length = 125
preview = true

[tool.isort]
profile = "black"
lines_after_imports = 2
line_length = 125
combine_as_imports = true
combine_star = true


[tool.pyright]
include = ["bot.py", "utilities/**/*.py", "extensions/**/*.py"]
useLibraryCodeForTypes = true
typeCheckingMode = "basic"
pythonVersion = "3.10"
strictListInference = true
strictDictionaryInference = true
strictSetInference = true
strictParameterNoneValue = true
reportMissingImports = "error"
reportUnusedImport = "error"
reportUnusedClass = "error"
reportUnusedFunction = "error"
reportUnusedVariable = "error"
reportGeneralTypeIssues = "error"
reportDuplicateImport = "error"
reportUntypedFunctionDecorator = "error"
reportUnnecessaryTypeIgnoreComment = "warning"


[build-system]
requires = ["poetry-core>=1.0.2b2"]
build-backend = "poetry.core.masonry.api"
