name: Type Coverage and Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11' ]

    name: "Type Coverage and Linting @ ${{ matrix.python-version }}"
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup Poetry @ ${{ matrix.python-version }}"
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: "Setup Python @ ${{ matrix.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
          cache: "poetry"

      - name: "Install Python deps @ ${{ matrix.python-version }}"
        env:
          PY_VER: "${{ matrix.python-version }}"
        run: |
          poetry env use "$PY_VER"
          poetry install --without=dev --no-interaction

      - uses: actions/setup-node@v3
        with:
            node-version: "17"
      - run: npm install --location=global pyright@latest

      - name: "Type Coverage @ ${{ matrix.python-version }}"
        run: |
          poetry run pyright

      - name: Lint
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_ISORT: true
          LINTER_RULES_PATH: /
          PYTHON_ISORT_CONFIG_FILE: pyproject.toml
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
